[program:smokeping]
command=/app/code/smokeping/bin/smokeping --config=/run/smokeping/config --nodaemon
user=www-data
priority=20
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
