[program:smokeping-fcgi]
command=spawn-fcgi -n -s /run/smokeping/fcgi.sock -M 0660 -U www-data -G www-data -- /app/code/smokeping/bin/smokeping_cgi /run/smokeping/config
user=www-data
priority=10
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
